### ISSUE TITLE
Error in name of plugin

### ISSUE THREAD

**Issue by aleshkin** [oh-my-fish/plugin-shark#1]
In repo this plugin named spark not shark

omf search spark                                                                                                                                                                        
Plugins
spark - ▁▂▃▅▂▇ in your shell

**Comment by sagebind** [comment]
Its similar, but a different plugin. The Spark plugin is here: https://github.com/oh-my-fish/plugin-spark. This is a deprecated fork of a rewrite of Spark in Fish, and is not available in the main repo.
