### ISSUE TITLE
md5sum is required

### ISSUE THREAD

**Issue by bpinto** [oh-my-fish/plugin-shark#2]
Do we need to install `md5sum` or can we use avoid it somehow? If we can't, we might want to add a note on the README.

```
fish: Unknown command 'md5sum'
~/.local/share/omf/pkg/weather/functions/weather.fetch.fish (line 1): echo $argv[1] | md5sum | cut -d " " -f 1
```

**Comment by coderstephen** [comment]
Er, wrong repo for issue? :stuck_out_tongue:

**Comment by coderstephen** [comment]
Well, sort of fixed now in the weather package.

**Comment by bpinto** [comment]
Oops, my bad! :stuck_out_tongue_winking_eye:
