### ISSUE TITLE
Array index out of bounds

### ISSUE THREAD

**Issue by eikooc** [oh-my-fish/plugin-shark#3]
Array index out of bounds error
```
~/.local/share/omf/pkg/shark/functions/shark.fish (line 28):     echo -n $sparks[(math "(($val)/1-($min)/1) * 2^8 / $fit + 1")]
                                                                                  ^
in function “shark”
```

**Comment by coderstephen** [comment]
Hmm... very odd. I'm not sure what is going on here. What is the output you get by simply running `shark 1 2 3`?

**Comment by eikooc** [comment]
Magically resolved today... Closing for now

**Comment by eikooc** [comment]
Okay so I can reproduce this with `shark 2 1.5` amongst others. This is just the smallest example I got to give the same error message

**Comment by eikooc** [comment]
`shark 1 0.1` works but `shark 1 0.10` errors as well

**Comment by coderstephen** [comment]
> Magically resolved today... Closing for now

The weather today is different probably.

> shark 1 0.1 works but shark 1 0.10 errors as well

I believe you, but I can't reproduce the error myself with any input. What version of Fish do you have? (`fish -v`)

**Comment by eikooc** [comment]
fish version is *2.2.0*

**Comment by eikooc** [comment]
The problem lies with `(printf "%s\n" $argv | sort --numeric-sort)`. The man page for sort says:
>-n, --numeric-sort
>            compare according to string numerical value

So the string representation of 1.51 is actually greater than 2 or 3 in this case. Use `--general-numeric-sort` instead

I'll open a pull request

Try this to reproduce
```
printf "%s\n" 2 3.1 1.5 4 | sort --numeric-sort
```
You can see the list is not sorted. If you feed this to `shark` the math expression evaluates to *-255* in one of the examples. Because the *max* and *min* variables are not set correctly.

This command should give you an index out of bounds error:
```
shark 2 3.1 1.5 4
```

**Comment by coderstephen** [comment]
Ah, that makes a lot of sense. Though I have to say, on my machine, either command flag yields the same sorted result. However, `--general-numeric-sort` is more correct. This is an issue upstream with the original Shark command then.

BTW, my GNU coreutils version is 8.23. That might make a difference.
